In [113]:
import pandas as pd
import numpy as np

In [114]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')
print(train.head(3))
print(test.head(3))
print(train.shape)
print(test.shape)

   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  

[3 rows x 81 columns]
     Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462        

In [115]:
train.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    70.049958   10516.828082     6.099315   
std     421.610009    42.300571    24.284752    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    59.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000  ...   
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726  ...   
std       1.112799    30.202904     20.645407   181.066207   456.098091  ...   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000  ...   
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000  ...   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...   

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  1460.000000  1460.000000    1460.000000  1460.000000  1460.000000   
mean     94.244521    46.660274      21.954110     3.409589    15.060959   
std     125.338794    66.256028      61.119149    29.317331    55.757415   
min       0.000000     0.000000       0.000000     0.000000     0.000000   
25%       0.000000     0.000000       0.000000     0.000000     0.000000   
50%       0.000000    25.000000       0.000000     0.000000     0.000000   
75%     168.000000    68.000000       0.000000     0.000000     0.000000   
max     857.000000   547.000000     552.000000   508.000000   480.000000   

          PoolArea       MiscVal       MoSold       YrSold      SalePrice  
count  1460.000000   1460.000000  1460.000000  1460.000000    1460.000000  
mean      2.758904     43.489041     6.321918  2007.815753  180921.195890  
std      40.177307    496.123024     2.703626     1.328095   79442.502883  
min       0.000000      0.000000     1.000000  2006.000000   34900.000000  
25%       0.000000      0.000000     5.000000  2007.000000  129975.000000  
50%       0.000000      0.000000     6.000000  2008.000000  163000.000000  
75%       0.000000      0.000000     8.000000  2009.000000  214000.000000  
max     738.000000  15500.000000    12.000000  2010.000000  755000.000000  

[8 rows x 38 columns]

In [116]:
# code2 - Compare train and test datasets
print('Train columns:', list(train.columns))
print('\nTest columns:', list(test.columns))
print('\nColumns in train but not in test:', set(train.columns) - set(test.columns))
print('\nColumns in test but not in train:', set(test.columns) - set(train.columns))

Train columns: ['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'Pool

In [117]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [118]:
train.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [119]:
train.nunique()

Id               1460
MSSubClass         15
MSZoning            5
LotFrontage       110
LotArea          1073
                 ... 
MoSold             12
YrSold              5
SaleType            9
SaleCondition       6
SalePrice         663
Length: 81, dtype: int64

In [120]:
# Create a DataFrame with null counts and unique value counts
testing = pd.DataFrame({
    'Null Count': train.isnull().sum(),
    'Unique Values': train.nunique()
})

# Display the DataFrame
testing

Null Count  Unique Values
Id                      0           1460
MSSubClass              0             15
MSZoning                0              5
LotFrontage           259            110
LotArea                 0           1073
...                   ...            ...
MoSold                  0             12
YrSold                  0              5
SaleType                0              9
SaleCondition           0              6
SalePrice               0            663

[81 rows x 2 columns]

In [121]:
train.drop(columns=['Alley','PoolQC','MiscFeature','Fence'],inplace=True,axis=1)

In [122]:
train.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 77, dtype: int64

In [123]:
testing = pd.DataFrame({
    'Data Type':train.dtypes,
    'Null Count': train.isnull().sum(),
    'Unique Values': train.nunique()
})

testing[testing['Null Count']!=0]

Data Type  Null Count  Unique Values
LotFrontage    float64         259            110
MasVnrType      object         872              3
MasVnrArea     float64           8            327
BsmtQual        object          37              4
BsmtCond        object          37              4
BsmtExposure    object          38              4
BsmtFinType1    object          37              6
BsmtFinType2    object          38              6
Electrical      object           1              5
FireplaceQu     object         690              5
GarageType      object          81              6
GarageYrBlt    float64          81             97
GarageFinish    object          81              3
GarageQual      object          81              5
GarageCond      object          81              5

In [124]:
import pandas as pd
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

In [125]:
#train['MasVnrType'].fillna('Unknown') # as majority of columns are unknown i cant remove

In [126]:
train.fillna(train.mean(numeric_only=True),inplace=True)

In [127]:
testing = pd.DataFrame({
    'Data Type':train.dtypes,
    'Null Count': train.isnull().sum(),
    'Unique Values': train.nunique()
})

testing[testing['Null Count']!=0]

Data Type  Null Count  Unique Values
MasVnrType      object         872              3
BsmtQual        object          37              4
BsmtCond        object          37              4
BsmtExposure    object          38              4
BsmtFinType1    object          37              6
BsmtFinType2    object          38              6
Electrical      object           1              5
FireplaceQu     object         690              5
GarageType      object          81              6
GarageFinish    object          81              3
GarageQual      object          81              5
GarageCond      object          81              5

In [128]:
## these all NA's has meaning of No basement and no fireplace i am assigninng with category of string 'NA'

In [129]:
Obj_col=train.select_dtypes(include='object').columns
train[Obj_col]=train[Obj_col].fillna('No_Basement_fireplace')

In [130]:
train.duplicated().sum()

np.int64(0)

In [143]:
from sklearn.preprocessing import OneHotEncoder

# Get categorical columns
cat_cols = train.select_dtypes(include='object').columns

# Initialize OneHotEncoder
encoder = OneHotEncoder(drop='first',sparse_output=False)

# Fit and transform the categorical columns
encoded_array = encoder.fit_transform(train[cat_cols])

# Get feature names for the encoded columns
encoded_feature_names = encoder.get_feature_names_out(cat_cols)

# Create DataFrame from encoded array
encoded_df = pd.DataFrame(encoded_array, columns=encoded_feature_names, index=train.index)

# Drop original categorical columns and add encoded ones to main dataset
df = train.drop(columns=cat_cols,inplace=True)
df = pd.concat([train, encoded_df], axis=1)
df.shape


(1460, 249)

In [146]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
pca=PCA()
sc=StandardScaler()

In [148]:
X_std=sc.fit_transform(df.drop(columns='SalePrice'))

In [150]:
components=pca.fit_transform(X_std)

In [151]:
components.shape

(1460, 248)

In [152]:
pca.components_

array([[-1.58608382e-04, -6.94795548e-03,  6.69772230e-02, ...,
        -7.22425090e-03, -4.75143817e-02,  1.01411216e-01],
       [ 5.06333918e-03, -1.10999660e-01,  7.90146751e-02, ...,
         1.48263188e-02,  7.39240650e-02, -9.61485076e-02],
       [ 3.19773743e-04, -3.11946842e-02,  6.99246136e-02, ...,
        -8.14833754e-03, -1.66718275e-02,  1.04651663e-02],
       ...,
       [ 0.00000000e+00,  2.56157630e-16,  2.93001367e-16, ...,
         0.00000000e+00, -2.77555756e-17,  2.11636264e-16],
       [-0.00000000e+00, -8.09720498e-17,  7.82039901e-17, ...,
        -3.46944695e-18, -4.16333634e-17, -3.24393290e-16],
       [ 0.00000000e+00,  1.81496544e-16,  3.08256912e-16, ...,
         9.71445147e-17, -9.36750677e-17, -2.66713734e-16]])

In [153]:
pca.explained_variance_.sum()

np.float64(248.16997943797114)

In [154]:
((pca.explained_variance_ratio_)*100).cumsum()

array([  6.86509594,  10.02532805,  12.90478285,  15.30180076,
        17.5520361 ,  19.50935698,  21.10656682,  22.65753006,
        23.96161929,  25.21761268,  26.42060083,  27.56909866,
        28.68037991,  29.73802087,  30.77491317,  31.8065302 ,
        32.81981291,  33.82102146,  34.75564872,  35.68258646,
        36.57603697,  37.45795656,  38.32068681,  39.16218567,
        40.0024215 ,  40.83801876,  41.64912885,  42.44125661,
        43.21403989,  43.97849119,  44.72818574,  45.47071843,
        46.20158536,  46.9170583 ,  47.61733014,  48.31467723,
        49.00787791,  49.68418212,  50.35629784,  51.02102408,
        51.68250975,  52.33428691,  52.9608031 ,  53.58597808,
        54.20467349,  54.81957546,  55.42624052,  56.02665294,
        56.62051723,  57.20218663,  57.77773214,  58.34318707,
        58.90410191,  59.46224402,  60.01089636,  60.55502873,
        61.09236063,  61.62029129,  62.13793112,  62.65153854,
        63.15629356,  63.65746464,  64.15630496,  64.65

In [159]:
pca=PCA(n_components=150)

In [160]:
components=pca.fit_transform(X_std)

In [161]:
pca.components_

array([[-0.00015861, -0.00694796,  0.06697722, ..., -0.00722425,
        -0.04751438,  0.10141122],
       [ 0.00506336, -0.11099968,  0.07901469, ...,  0.0148263 ,
         0.07392407, -0.09614849],
       [ 0.00031978, -0.03119468,  0.06992453, ..., -0.00814833,
        -0.01667182,  0.01046516],
       ...,
       [-0.07829048,  0.01685897, -0.03808623, ...,  0.07959172,
         0.06020825,  0.01103476],
       [ 0.04923758, -0.0530028 , -0.02814107, ...,  0.08132397,
         0.08917065,  0.05371486],
       [-0.06165959,  0.04100205, -0.08947193, ..., -0.06162521,
        -0.04105962, -0.02374706]])

In [162]:
((pca.explained_variance_ratio_)*100).cumsum()

array([ 6.86509594, 10.02532805, 12.90478285, 15.30180076, 17.5520361 ,
       19.50935698, 21.10656682, 22.65753005, 23.96161927, 25.21761265,
       26.42060079, 27.56909861, 28.68037984, 29.73802077, 30.77491295,
       31.80652992, 32.81981259, 33.82102112, 34.75564819, 35.68258586,
       36.57603621, 37.45795572, 38.32068586, 39.16218466, 40.00242027,
       40.83801735, 41.64912632, 42.44125326, 43.21403593, 43.97848681,
       44.72818109, 45.47071305, 46.2015795 , 46.91705187, 47.61732289,
       48.31466933, 49.00786898, 49.6841729 , 50.3562877 , 51.02101286,
       51.68249735, 52.33427189, 52.96078601, 53.58595833, 54.20465068,
       54.81955037, 55.42621423, 56.02661804, 56.62046601, 57.20213242,
       57.77767498, 58.34312607, 58.90402964, 59.46216376, 60.01080644,
       60.55492764, 61.09223985, 61.62016584, 62.13779387, 62.65139204,
       63.15613476, 63.65727639, 64.15610853, 64.65217284, 65.14393638,
       65.63175018, 66.11357335, 66.58847833, 67.06111738, 67.53

In [165]:
new_col=['PC'+str(i)for i in range(1,151)]
pcs=pd.DataFrame(components,columns=new_col)
pcs.head(3)

PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0  4.264438 -1.928444 -0.486946 -1.575763 -1.195373 -2.165042 -0.179908   
1  0.049746  3.040711  0.344505 -0.655975  0.935264 -0.652838  0.898327   
2  5.014508 -1.285868 -0.039154 -0.744619 -0.870040 -2.336848  0.405102   

        PC8       PC9      PC10  ...     PC141     PC142     PC143     PC144  \
0 -1.418721  1.640663 -0.524561  ... -0.523262 -0.135671  0.548611  0.039960   
1 -0.812293 -0.414956 -0.148360  ...  0.335208  0.966774 -0.319868 -1.097087   
2 -1.889311  1.662362 -0.772935  ... -0.461331 -0.131187  0.385808 -0.394935   

      PC145     PC146     PC147     PC148     PC149     PC150  
0 -0.073926 -0.190520  0.212483 -0.239571  0.023108  0.265294  
1  0.692127  0.090408 -0.886719  0.541528  0.868538 -1.568362  
2 -0.567397 -0.252939  0.471783  0.408674  0.296660  0.231664  

[3 rows x 150 columns]

In [166]:
pcs['Sales_Price']=df.SalePrice

In [167]:
pcs.head(3)

PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0  4.264438 -1.928444 -0.486946 -1.575763 -1.195373 -2.165042 -0.179908   
1  0.049746  3.040711  0.344505 -0.655975  0.935264 -0.652838  0.898327   
2  5.014508 -1.285868 -0.039154 -0.744619 -0.870040 -2.336848  0.405102   

        PC8       PC9      PC10  ...     PC142     PC143     PC144     PC145  \
0 -1.418721  1.640663 -0.524561  ... -0.135671  0.548611  0.039960 -0.073926   
1 -0.812293 -0.414956 -0.148360  ...  0.966774 -0.319868 -1.097087  0.692127   
2 -1.889311  1.662362 -0.772935  ... -0.131187  0.385808 -0.394935 -0.567397   

      PC146     PC147     PC148     PC149     PC150  Sales_Price  
0 -0.190520  0.212483 -0.239571  0.023108  0.265294       208500  
1  0.090408 -0.886719  0.541528  0.868538 -1.568362       181500  
2 -0.252939  0.471783  0.408674  0.296660  0.231664       223500  

[3 rows x 151 columns]

In [168]:
from sklearn.linear_model import SGDRegressor
sgt=SGDRegressor()

In [171]:
sgt_parameter={
    'penalty' : ['l2', 'l1', 'elasticnet'],
    'learning_rate':[0.10,0.15,0.20,0.25],
    'alpha':[0.1,0.01,0.001,0.0001],
    'n_iter_no_change':[5,10,15,20],
    'max_iter':[500,750,1000,1250]
}

In [173]:
from sklearn.model_selection import train_test_split, KFold

In [176]:
X=pcs.drop(columns='Sales_Price')
y=pcs['Sales_Price']

In [177]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [178]:
sgt.fit(X_train,y_train)

SGDRegressor()

In [179]:
y_pred=sgt.predict(X_test)
y_pred

array([ 9.32358059e+05, -8.59687847e+05, -2.69782910e+06, -2.03923788e+06,
        1.12807883e+05,  2.27806598e+06,  5.14655536e+05,  2.82016854e+06,
        2.15740610e+06, -1.07366704e+06, -3.74745435e+05, -8.82838520e+05,
       -1.81904022e+07,  4.23517091e+05, -7.86314942e+05,  1.47038947e+06,
        1.00185882e+06, -3.44975517e+05, -5.12161731e+05,  8.47112262e+05,
        2.17597498e+06,  4.83045640e+05,  1.84214088e+05, -6.76698305e+06,
        5.50351031e+04,  1.55135832e+05, -2.32055825e+05, -3.35355502e+06,
       -1.16437996e+06,  5.33620936e+05, -4.76019038e+05,  1.26789921e+06,
        1.38132864e+06, -6.79187610e+05,  1.35768245e+05, -1.05774201e+06,
        1.15550432e+06,  1.41409890e+06, -3.45948373e+04, -7.66489336e+05,
        4.24819083e+05,  1.63896306e+06, -5.07303460e+05,  1.02096585e+06,
        1.39782748e+06,  8.33271919e+05, -2.08546567e+05,  5.45516931e+05,
        4.54980224e+05,  2.05031821e+05, -5.65708445e+06,  3.38954275e+05,
        1.46932803e+06,  

In [180]:
from sklearn.metrics import mean_absolute_error,root_mean_squared_error,mean_squared_error,r2_score

-0.00029037058069802946