In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
import os
os.chdir('D:\Documents')
os.getcwd()


'D:\\Documents'

In [7]:
data=pd.read_csv('Social_Network_Ads.csv')
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [8]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [9]:
data.info

<bound method DataFrame.info of       User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]>

In [10]:
data.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [14]:
#parameters fixing
X=data[['Age','EstimatedSalary']]
y=data[['Purchased']]


In [16]:
y

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [19]:
len(X_train)

320

In [20]:
len(y_test)

80

In [21]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(X_train,y_train)

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [23]:
pred= log_reg.predict(X_test)
pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [24]:
pred.sum()

np.int64(23)

In [ ]:
#some times you wont get a proper result if you see the number wrong model wont perform better
#Scalling is import

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [35]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train =sc.fit_transform(X_train)
X_test =sc.transform(X_test)

array([[-0.74898305],
       [ 1.3351437 ],
       [ 1.3351437 ],
       [-0.74898305],
       [ 1.3351437 ],
       [ 1.3351437 ],
       [-0.74898305],
       [ 1.3351437 ],
       [-0.74898305],
       [-0.74898305],
       [ 1.3351437 ],
       [-0.74898305],
       [-0.74898305],
       [-0.74898305],
       [-0.74898305],
       [-0.74898305],
       [ 1.3351437 ],
       [-0.74898305],
       [ 1.3351437 ],
       [ 1.3351437 ],
       [ 1.3351437 ],
       [-0.74898305],
       [ 1.3351437 ],
       [-0.74898305],
       [-0.74898305],
       [ 1.3351437 ],
       [ 1.3351437 ],
       [ 1.3351437 ],
       [ 1.3351437 ],
       [-0.74898305],
       [-0.74898305],
       [-0.74898305],
       [ 1.3351437 ],
       [ 1.3351437 ],
       [ 1.3351437 ],
       [-0.74898305],
       [-0.74898305],
       [ 1.3351437 ],
       [-0.74898305],
       [-0.74898305],
       [-0.74898305],
       [-0.74898305],
       [ 1.3351437 ],
       [ 1.3351437 ],
       [ 1.3351437 ],
       [-0

In [36]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(X_train,y_train)

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [38]:
pred1=log_reg.predict(X_test)
pred1

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [39]:
pred1.sum()

np.int64(21)

In [41]:
y_proba=log_reg.predict_proba(X_test)
y_proba

array([[0.73536624, 0.26463376],
       [0.02499291, 0.97500709],
       [0.97738552, 0.02261448],
       [0.14099766, 0.85900234],
       [0.98372604, 0.01627396],
       [0.94193174, 0.05806826],
       [0.12159382, 0.87840618],
       [0.90768807, 0.09231193],
       [0.60561172, 0.39438828],
       [0.59229537, 0.40770463],
       [0.8485374 , 0.1514626 ],
       [0.32653013, 0.67346987],
       [0.99003138, 0.00996862],
       [0.99753285, 0.00246715],
       [0.87662325, 0.12337675],
       [0.57526162, 0.42473838],
       [0.34002528, 0.65997472],
       [0.33292738, 0.66707262],
       [0.84701151, 0.15298849],
       [0.10332004, 0.89667996],
       [0.9958666 , 0.0041334 ],
       [0.91565969, 0.08434031],
       [0.68915816, 0.31084184],
       [0.03669878, 0.96330122],
       [0.99821601, 0.00178399],
       [0.50623018, 0.49376982],
       [0.46958138, 0.53041862],
       [0.8498944 , 0.1501056 ],
       [0.0160748 , 0.9839252 ],
       [0.99809445, 0.00190555],
       [0.

In [42]:
y_proba[:,1]

array([0.26463376, 0.97500709, 0.02261448, 0.85900234, 0.01627396,
       0.05806826, 0.87840618, 0.09231193, 0.39438828, 0.40770463,
       0.1514626 , 0.67346987, 0.00996862, 0.00246715, 0.12337675,
       0.42473838, 0.65997472, 0.66707262, 0.15298849, 0.89667996,
       0.0041334 , 0.08434031, 0.31084184, 0.96330122, 0.00178399,
       0.49376982, 0.53041862, 0.1501056 , 0.9839252 , 0.00190555,
       0.40259654, 0.00953564, 0.74614456, 0.06845804, 0.65197003,
       0.19893183, 0.15872643, 0.24145353, 0.00981295, 0.00737694,
       0.43212687, 0.01515215, 0.00436267, 0.29002883, 0.00580206,
       0.92096911, 0.04688003, 0.09142778, 0.49774364, 0.06645817,
       0.03957917, 0.90960658, 0.18619616, 0.04085358, 0.30105991,
       0.01226874, 0.9868609 , 0.1533577 , 0.09999613, 0.10609835,
       0.26336592, 0.12053976, 0.91530323, 0.08734701, 0.03657945,
       0.29145561, 0.61111858, 0.9608016 , 0.24048436, 0.37194354,
       0.98138684, 0.01555263, 0.02940231, 0.00397863, 0.39341

In [43]:
df=pd.DataFrame()
df['Proba']=y_proba[:,1]
df['prediction']=pred1
df['Actual']=y_test
df

Proba  prediction  Actual
0   0.264634           0     0.0
1   0.975007           1     NaN
2   0.022614           0     NaN
3   0.859002           1     NaN
4   0.016274           0     NaN
..       ...         ...     ...
75  0.098105           0     NaN
76  0.989761           1     0.0
77  0.657593           1     0.0
78  0.089682           0     0.0
79  0.287349           0     NaN

[80 rows x 3 columns]

In [44]:
df=pd.DataFrame()
df['Proba']=y_proba[:,1]
df['prediction']=pred1
df['Actual']=y_test.reset_index(drop=True)
df

Proba  prediction  Actual
0   0.264634           0       0
1   0.975007           1       1
2   0.022614           0       0
3   0.859002           1       1
4   0.016274           0       0
..       ...         ...     ...
75  0.098105           0       0
76  0.989761           1       1
77  0.657593           1       1
78  0.089682           0       0
79  0.287349           0       1

[80 rows x 3 columns]